version: '3.8'

services:
  backend-startax:
    build:
      context: .
    image: backend-startax:latest
    restart: always
    ports:
      - "5001:5001"
    volumes:
      - /home/admin/startax-bucket:/home/admin/startax-bucket  # <=== volume local:container
    networks:
      - startax-network

networks:
  startax-network:
    external: true
